로딩스피너 유형(플로팅) 추가
NHJeans/Deepening-Project pull request #21
Opened 2024-07-12 14:36 UTC by Ahnjonghyun87

![loadingFloater](https://github.com/user-attachments/assets/91284707-dfaa-4c80-97f9-32151e39a993)

src/components/loading/LoadingFloater.tsx 파일 import하시면 됩니다.

빙글빙글 도는걸 원하시면 LoadingSpinner 쓰시면 됩니다

2024-07-13 03:12 UTC, phantom2115 requested changes
너무 귀엽네요~ 고생하셨습니다

2024-07-13 03:13 UTC, phantom2115 approved these changes
너무 귀엽네요 고생하셨습니다

2024-07-13 07:41 UTC, NHJeans approved these changes
종현님 고생하셨습니다~!!

2024-07-13 10:20 UTC, merged

2024-07-14 03:13 UTC, hyeonseok98 commented
너무 귀엽네요~!! 고생하셨습니당